# About

This work is based on this section of the Quarto manual <https://quarto.org/docs/journals/templates.html#replacing-partials> To see the LaTeX templates that Quarto is using start here: <https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/formats/pdf/pandoc/template.tex>

This template makes a custom title page using the information in the YAML (from the `xyz.qmd` for an single doc and from `index.qmd` for a Quarto book). The default document classes in Quarto are `scrbook` and `srcartcl`, but these templates work for other document classes too. There are some other classes in the `cls` folder (krantz, svmono, elsevier). The static title pages are inspired from [Latex Templates](http://www.latextemplates.com/cat/title-pages#google_vignette). 

## Audience

This is written assuming you are a LaTeX user and thus already know how to do what you want in LaTeX, but you need to figure out how to tell Quarto to do what you want. Skim the chapter on [LaTeX document structure](06-latex.qmd) if you are unfamiliar with LaTeX so you know what I am talking about when I reference parts of a LaTeX document.

Quarto has included a variety of YAML options you can use to alter your LaTeX document by passing in things like fontenc package options or geometry options in the YAML. I largely ignore all that and just pass in the header file I want. As a LaTeX user, I find all those YAML options confusing and I spend hours digging through the Quarto source code to figure out exactly how they are using the YAML options.

That said, for quarto_titlepages, I am mainly just swapping out the `before-body.tex` partial (the part that specs the title and front matter) and adding stuff to the header (before `begin{document}`).


## Approach I took

There are 2 approaches that I considered.

1.  Use the `title.tex` partial (which defines things like title and author) and then redefine the `\maketitle` command. Google and you'll find examples. I find `\maketitle` really irritating and is a constant headache to make custom title pages with it. But maybe you love it; in which case, try that approach.
2.  Use `before-body.tex` partial to get rid of the `\maketitle` call and use my own `\begin{frontmatter}...\end{frontmatter}` section. I find this much more straightforward for creating custom titlepages. So that's the approach I took.

## Author lists

When recreating a government report title page, I don't get to choose how the page looks. It has to look a very particular way. I find it easiest to just create that look manually rather than trying to figure out how to get the authblk LaTeX package to do what I want. authblk is a widely used LaTeX package which has helper functions for creating author lists along with affiliations.

If you use authblk in your titlepage, you will need to write your `\author` and `affil` definitions in `title.tex` and then you can use those in `before-body.tex` in your `\begin{titlepage}...\end{titlepage}` code. See the [LaTeX document structure](06-latex.qmd) page for tips.

## More notes

See the [notes chapter](07-notes.html) for some notes I took along the way.


