# Pandoc template help

The files that appear in the template-partials: line of the YAML are Pandoc Templates with LaTeX
Pandoc templating [](https://pandoc.org/MANUAL.html#templates)

`$--` is a Pandoc comment
`%` is a LaTeX comment

## Comments

If I want to comment out a line, I use both though maybe `$--` works.
```
% $-- $if(subtitle)$ ... $endif$
```

## If statements

```
$if(subtitle)$ ... $endif$
```

Here `subtitle` is true if the YAML has "subtitle: " and false otherwise

`$subtitle$` (with `$..$`) is the value of subtitle in the YAML

```
$if(subtitle)${\large\textit{$subtitle$}}$endif$ 
```
prints the subtitle in large text. `\large` is LaTeX

`$if(by-author/allbutlast)$` means if there is more than one author
since if there is only one author then there is no "allbutlast" value

`$if(by-author/last)$` tests if there is a last author. If there is at least one author, this will be true.

## for loops

```
$for(by-author)$%
{\large{$by-author.name.literal$}}$sep${\large{ AND }}
$endfor$%
```

This is a for loop across all the authors and prints each author name. The `$sep$` bit says what to put between the names. In this case it would be AND. So `Jane Doe AND Ashkar Kumar`

## Number appearances

The Pandoc template can number the author affiliations and will figure the duplicates.

```
$for(by-author)$%
{\large{$by-author.name.literal$}}%
$for(by-author.affiliations)$%
{\textsuperscript{$it.number$}}$sep$\textsuperscript{,}%
$endfor$%
$sep$, %
$endfor$
```

This is assigning a number to each affiliation name and then adds it as a superscript to the author name. It will figure out the duplicates.

