---
title: "quarto titlepages"
subtitle: "LaTeX title pages with Quarto"
page-layout: full
---

[quarto titlepages](https://github.com/nmfs-opensci/quarto_titlepages) is a collection of Pandoc template partials (Pandoc template + LaTeX) and LaTeX header files to create custom title pages for PDF.

# Preface 

This is written mainly for LaTeX users. Quarto has included a variety of YAML options so that you can alter your LaTeX by passing in things like fontenc package options or geometry options in the YAML. I largely ignore all that and just pass in the header file I want. As a LaTeX user, I find all those YAML options confusing and I spend hours digging through the Quarto source code to figure out exactly how they are using the YAML options. However, I am just swapping out the `before-body.tex` partial (the part that specs the title and front matter) and adding stuff to the header (before `begin{document}`).


## Approach I took

There are 2 approaches that I considered.

1.  Use the `title.tex` partial (which defines things like title and author) and then redefine the `\maketitle` command. Google and you'll find examples. I find `\maketitle` really irritating and is a constant headache to make custom title pages. But maybe you love it; in which case, try that approach.
2.  Use `before-body.tex` partial to get rid of the `\maketitle` call and use my own `\begin{frontmatter}...\end{frontmatter}` section. I find this much more straightforward for creating custom titlepages. So that's the approach I took.

## Author lists

When recreating a government report title page, I don't get to choose how the page looks. It has to look a very particular way. I find it easiest to just create that look manually rather than trying to figure out how to get the authblk LaTeX package to do what I want. authblk is a widely used LaTeX package which has helper functions for creating author lists along with affiliations.

If you use authblk in your titlepage, you will need to write your `\author` and `affil` definitions in `title.tex` and then you can use those in `before-body.tex` in your `\begin{title}...\end{title}` code.